---

- block:
    - name: install hashicorp gpg 
      shell:
        cmd: wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg

    - name: Verify key fingerprint 
      shell:
        cmd: gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
      register: fingerPrint

    - block:
        - name: print out fingerprint 
          debug:
            var: fingerPrint 

        - name: Sleep for {{ timeout }} seconds and continue with play
          ansible.builtin.wait_for:
            timeout: '{{ timeout }}'
          delegate_to: localhost
          when: interactive | default(false)
      when: not debug | default(false)

    - name: Add the official HashiCorp repository
      shell:
        cmd: echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list

    - name: Install hasicorp tools
      apt:
        name:
          - terraform
          - packer 
        update_cache: true

    - name: verify install
      shell: terraform -help
      register: terraform
  when: ansible_distribution == 'Ubuntu'

- block:
  - name: add the official HashiCorp Linux repository
    shell:
      cmd: sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo

  - name: Install hashicorp tools 
    yum:
      name: 
        - terraform
      update_cache: true
  when: ansible_distribution == 'Red Hat'


