---
#########################################################
#             Manage packages          #
#########################################################
- hosts: "{{ node }}"
  become: true
  roles:
    - packages
    # - patch 
    
