---
########################################################
#                   Patch the system                   #
########################################################
- hosts: docker, plex
  become: true
  roles:
    - role: patch
