---
########################################################
#              Semaphore the system                    #
########################################################
- hosts: localhost
  become: true
  roles:
    - role: semaphore
