---
########################################################
#              Tailscale the system                    #
########################################################
- hosts: '{{ node }}'
  become: true
  roles:
    - role: tailscale
      when: tailscale_enabled | default(false)
